# Generated by Django 5.2.6 on 2025-09-08 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lycee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('titre', models.CharField(max_length=200)),
                ('objectif', models.TextField()),
                ('etat', models.CharField(choices=[('todo', 'À faire'), ('progress', 'En cours'), ('done', 'Terminé')], default='todo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('membres', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('lycee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='core.lycee')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('activites', models.TextField()),
                ('difficultes', models.TextField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='core.equipe')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='core.seance')),
            ],
        ),
    ]
