# Generated by Django 5.2.6 on 2025-09-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='nombre_eleves',
            field=models.IntegerField(default=1),
        ),
    ]
