# Generated by Django 5.2.6 on 2025-09-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_equipe_membres_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='fait_par',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
