# Generated by Django 5.2.6 on 2025-09-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_membre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapport',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='profil',
            name='chef_equipe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Membre',
        ),
    ]
