# Generated by Django 5.2.6 on 2025-09-16 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_rapport_options_profil_chef_equipe_profil_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='etat',
        ),
        migrations.CreateModel(
            name='EtatSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('todo', 'À faire'), ('progress', 'En cours'), ('done', 'Terminé')], default='todo', max_length=10)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats', to='core.equipe')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats', to='core.seance')),
            ],
            options={
                'unique_together': {('equipe', 'seance')},
            },
        ),
    ]
