# Generated by Django 5.2.6 on 2025-09-16 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_seance_etat_etatseance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConseilPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommandations', models.TextField(help_text='Indiquez les points clés, la méthode, le déroulement.', verbose_name='Conseils pour animer la séance')),
                ('exercices_pratiques', models.TextField(help_text="Liste d'exercices ou d'activités à proposer aux élèves.", verbose_name='Exercices pratiques')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conseils_pedagogiques', to='core.seance')),
            ],
            options={
                'verbose_name': 'Conseil pédagogique',
                'verbose_name_plural': 'Conseils pédagogiques',
                'ordering': ['-date_creation'],
            },
        ),
    ]
