# Generated by Django 5.2.6 on 2025-09-19 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_conseilpedagogique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='mois',
        ),
    ]
